name: ields
url: ""
files_url: /data
description: Fields - blog about mathematics, physics and philosophy.
permalink: /articles/:title
markdown: kramdown
lsi: true
exclude: [Gemfile, Gemfile.lock, CNAME, README.md, publish.sh, Makefile]
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      toc: true

sass:
  style: :compressed
